---
name: Create Release for rune-service-2

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'rune-service-2/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"
      - name: Release
        if: ${{ inputs.config-file }}
        run: echo RELEASE
