---
name: Create Release for rune-service

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'rune-service/**'

jobs:
  ci:
    if: "!startsWith(github.event.head_commit.message, 'chore(main): release') && github.event.head_commit.author.name != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"
      - name: Release
        if: ${{ inputs.config-file }}
        run: echo RELEASE
