---
name: CI for rune-service

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
  push:
    paths:
      - 'rune-service/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"
      - name: Release
        if: ${{ inputs.release-version }}
        run: echo RELEASE ${{ inputs.release-version }}
