---
name: CI for rune-service-2

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'rune-service-2/**'

jobs:
  ci:
    if: "inputs.release-version || !startsWith(github.event.head_commit.message, 'chore(main): release') && github.event.head_commit.author.name != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"
      - name: Release
        if: ${{ inputs.release-version }}
        run: echo RELEASE ${{ inputs.release-version }}
