---
name: Create Release Please Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rune-service/**'
      - 'rune-service-2/**'
      - 'rune-service-3/**'

jobs:
  release-please:
    outputs:
      rune-service-version: ${{ steps.release.outputs.rune-service--version }}
      rune-service-2-version: ${{ steps.release.outputs.rune-service-2--version }}
      rune-service-3-version: ${{ steps.release.outputs.rune-service-3--version }}
    if: "startsWith(github.event.head_commit.message, 'chore(main): release')"
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          include-component-in-tag: true
          skip-github-pull-request: true
      - name: Dump Release Please Output
        env:
          RP_OUTPUTS: ${{ toJson(steps.release.outputs) }}
        run: echo "See RP_OUTPUTS in env."

  release-rune-service:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.rune-service-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Release Please Output
        env:
          RP_OUTPUTS: ${{ toJson(needs.release-please.outputs) }}
        run: echo "See RP_OUTPUTS in env."

  release-rune-service-2:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.rune-service-2-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Release Please Output
        env:
          RP_OUTPUTS: ${{ toJson(needs.release-please.outputs) }}
        run: echo "See RP_OUTPUTS in env."

  release-rune-service-3:
    needs: [release-please]
    if: ${{ needs.release-please.outputs.rune-service-3-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump Release Please Output
        env:
          RP_OUTPUTS: ${{ toJson(needs.release-please.outputs) }}
        run: echo "See RP_OUTPUTS in env."

