---
name: Create Release Please Pull Requests (release-applications/**) - Phalanx

on:
  workflow_dispatch:
  push:
    branches:
      - 'release-applications/**'

jobs:
  create-release-please-pull-requests:
    # This job must not run when Release Please pull requests are merged to main, since this causes an pull request
    # with incorrect version number and changelog to be created for the component, that was released.
    if: "!startsWith(github.event.head_commit.message, 'chore: release applications from branch ') && github.event.head_commit.author.name != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Release Please
        uses: googleapis/release-please-action@v4
        with:
          skip-github-release: true
          target-branch: ${{ github.ref_name }}
          config-file: release-please/release-please-config-release-applications.json
          manifest-file: release-please/.release-please-manifest-release-applications.json
