---
name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rune-service/**'
      - 'rune-service-2/**'
      - 'rune-service-3/**'

jobs:
  create-release-please-pull-requests:
    if: "startsWith(github.event.head_commit.message, 'chore(main): release')"
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Release Please
        uses: googleapis/release-please-action@v4
        with:
          include-component-in-tag: true
          skip-github-pull-request: true
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"
