---
name: Print GitHub context

on:
  workflow_dispatch:
    inputs:
      test:
        required: false
        default: ''
        type: string
        description: 'Test'
  push:
    branches:
      - main
    paths:
      - 'rune-service/**'

jobs:
  print-github-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"

  print-github-context-2:
    uses: ./.github/workflows/print-github-context-2.yaml
