---
name: Release Please

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rune-service/**'
      - 'rune-service-2/**'
      - 'rune-service-3/**'

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Release Please
        uses: googleapis/release-please-action@v4
        with:
          include-component-in-tag: true
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "See GITHUB_CONTEXT in env. Triggering actor - ${{ github.triggering_actor }}"

  release-please-output:
    runs-on: ubuntu-latest
    needs: [release-please]
    steps:
      - name: Dump GitHub context
        env:
          RP_OUTPUT: ${{ toJson(needs.release-please.outputs) }}
        run: echo "See RP_OUTPUT in env."
